name: 'chatgpt-create-unit-tests'
description: 'Analyse a Pull Request and adds unit tests if necessary / possible'
outputs:
  comment:
    description: 'A comment'
runs:
  using: 'docker'
  image: 'Dockerfile'